# Generated by Django 4.1.1 on 2022-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restocked',
            field=models.BooleanField(default=False),
        ),
    ]
